using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests
{
    [TestClass]
    public class AssemblyBrowserTest
    {
        [TestMethod]
        public void GetAssemblyInfoTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}