using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests
{
    [TestClass]
    public class FakerTest
    {
        [TestMethod]
        public void CreateTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void CreateTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void TryGenerateAbstractTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}