using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests
{
    [TestClass]
    public class LongGeneratorTest
    {
        [TestMethod]
        public void CreateTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}