using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests
{
    [TestClass]
    public class TracerClassTest
    {
        [TestMethod]
        public void GetTraceResultTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StartTraceTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StopTraceTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}